name: Test Release

on:
  workflow_dispatch:
    inputs:
      release_tag_name_input:
        description: 'Release Tag Name <X.X.X>'
        required: true


jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      release_upload_url: ${{ steps.create_release.outputs.upload_url }}
      package_version: ${{ steps.create_tags.outputs.package_version }}
      tag_version: ${{ steps.create_tags.outputs.tag_version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Create Release Vars
        id: create_tags
        run: |
          case "${RELEASE_TAG_NAME_INPUT:0:1}" in
            v)
              echo "RELEASE_NAME=${RELEASE_TAG_NAME_INPUT:1}" >> $GITHUB_ENV
              echo "RELEASE_TAG_NAME=$RELEASE_TAG_NAME_INPUT" >> $GITHUB_ENV
              echo "::set-output name=package_version::${RELEASE_TAG_NAME_INPUT:1}"
              echo "::set-output name=tag_version::$RELEASE_TAG_NAME_INPUT"
              ;;
            [0-9])
              echo "RELEASE_NAME=$RELEASE_TAG_NAME_INPUT" >> $GITHUB_ENV
              echo "RELEASE_TAG_NAME=v$RELEASE_TAG_NAME_INPUT" >> $GITHUB_ENV
              echo "::set-output name=package_version::$RELEASE_TAG_NAME_INPUT"
              echo "::set-output name=tag_version::v$RELEASE_TAG_NAME_INPUT"
              ;;
            *)
              exit 1
              ;;
          esac
        env:
          RELEASE_TAG_NAME_INPUT: ${{ github.event.inputs.release_tag_name_input }}


  linux:
    runs-on: ubuntu-latest
    needs: setup
    env:
      PKG_VERSION: ${{ needs.setup.outputs.package_version }}
      TAG_VERSION: ${{ needs.setup.ouputs.tag_version }}
    steps:
      - name: Create test assets
        run: |
          touch bitwarden_${{ env.PKG_VERSION }}_amd64.snap
          touch bitwarden.${{ env.PKG_VERSION }}.nupkg
          touch Bitwarden-${{ env.PKG_VERSION }}.pkg

      - name: Upload test files
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bitwarden_${{ env.PKG_VERSION }}_amd64.snap
            bitwarden.${{ env.PKG_VERSION }}.nupkg
            Bitwarden-${{ env.PKG_VERSION }}.pkg
          draft: true
          prerelease: false
          tag_name: ${{ env.TAG_VERSION }}
          name: Version ${{ env.PKG_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
